language: go

sudo: false

go: "1.x"

install: make install-deps

script:
  - make build
  - ./build/chaosmonkey_linux_amd64 --version

deploy:
  provider: releases
  file:
    - build/chaosmonkey_darwin_amd64
    - build/chaosmonkey_linux_amd64
    - build/SHA256SUMS
    - build/chaosmonkey.rb
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: Vvjl8vtvbknPraGcm0OCLPPSvRM08Nnw2b21LuJON+k2928cYjDz2KhuOJVNyMPtP+QD6oQ1Hwhm9L+/92VU/62zg4MFc01flWrQlWQAHkXbdqr7Hna5VLUV4ZrMqZbtpxLrh6Ee85VDOSELOW1QlD+NT3VbKquSa7CBQ0XEDAL1vqytew/CZxOJOINY0p7sPzGp2pJVztw1PoU6ehyxjmEW0eEo+Q/Jk+GeEoTbU5R1WZuQUt+Nd5nIK2ZqyVIxVZ5TbIDCDZalXcqAzIQGOkYZ+xXGUjIT1K9dR4MAADCmYPYFzeSZuZZOyYeoQ2kJ2LYaeFI1XvUsC3SV2L2YydzAZzmD+fWv/YdwoBXsUzk1v6rTqIQMl4EzKrjMNF9Rs33ygvG0+bjC3ssF7YuLFCG1ET4XkxxxBZ3CH3YkJfs0vrID7jhQIKIa95MxhkBX0DCw4+PeD0HpkR5FJzMscvCtsZIXevCX03eojOBAygvlqMGsn0vQqozss473lQYfxZfZjjyYPm4V0t/wU3LiqoMvncgNpHdXJ3szTXxd2tQODJ/KjRlYu1EeR3Bqp+FicqvvP3yHBpaRSKMsVoB6g7zMEe2VMnZvwAIM0QdvluB8CKoMOOP+hcunoILC7qCaUVGqGwirksOcAgWuL/9US3hfLZMpvCC0X6pGKlvzMNs=
