language: go

sudo: false

go:
  - 1.7
  - tip

install: make deps

script:
  - make build
  - ./build/chaosmonkey_linux_amd64 --version

branches:
  only:
    - master

matrix:
  allow_failures:
    - go: tip

deploy:
  provider: releases
  file:
    - build/chaosmonkey_darwin_amd64
    - build/chaosmonkey_linux_amd64
    - build/SHA256SUMS
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: UznHHV+CMO2ZhNfXg2+b247UuAqSerS0KVhmML6/ST0Vn5u5JgFv4fLbJgB5paJHEPOVf64NhD7+5HZmpswAXsdffdAS/SEf7cV0f0GXBEtuMC4S7ETzxqA3RqbI8Dg7yqQkUjdRiIkoEcTRQi1HQG3/1EVCsup4YjvYMTyaNk1F+Wia6pxd50a6YEHzrvzIPxo2Q1IAhS8FbKBqmbiQnYDvRDPbWnbfyOb1nuilUyYQO1p5vjt9lXmg+4+3ufNHL/oOORVaa3+Y8aQLHOZLLSagfPdcS0IbbA6myDdWuUgcWNbtdo7IEvq5M0F0jEso6HOaQRW7a9o29Vt67cetSM1eb9j9m3m33H16lrFQs3jFe/QaxnZYUxKE7fgwTSpcEgz/MsjvI+edBbyy1GZpyqmre75Wn2++wV6XrLCaXN9dyqTs8cYMLWEpkaQ39dUSQSG+NTkLVCrH7goStaSHhJdyv5Bcwp/awZ4l3gjMV20g2au0Bo+yUsJbJKb4NgxWC1O89CNJq4F6I+9cqd0hTdwD6PXc9cnxhY66/EGjRVNZPiX5QF93XMJrjZ/MmKz/iEPy7KL687ACyp0PNKuSluUvh/ymV5Al/ujm88n6En2F2ZQW7GpaBQt77p+FY9QDKK9vaP71UXkESy+VapG4pkxR5M++u/3go/PITSm0Hds=
