language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

install: make deps

script:
  - make build
  - ./build/chaosmonkey_linux_amd64 --version

branches:
  only:
    - master

matrix:
  allow_failures:
    - go: tip
